-- Writes Releases.lua: the latest version of each Allemano addon and its newest release note, read
-- from the sibling repositories (TOC "## Version" and the top entry of CHANGELOG.md).
-- The Hub cannot ask the internet, so "update available" and News come from this file. Run it
-- before releasing a new Hub version:   lua tools/gen_releases.lua
local here = arg and arg[0] and arg[0]:gsub("\\", "/"):match("^(.*)/tools/[^/]*$") or "D:/Projects/allemano-addons/AllemanoHub"
local repos = here:gsub("/[^/]*$", "")

-- id, repository folder, TOC name
local addons = {
  { "hush", "Hush", "Hush.toc" },
  { "altboard", "AltBoard", "AltBoard.toc" },
  { "craftboard", "CraftBoard", "CraftBoard.toc" },
  { "art", "AllemanoRaidTools", "AllemanoRaidTools.toc" },
  { "alc", "ArbiterLootCouncil", "ArbiterLootCouncil.toc" },
  { "session-tracker", "SessionTracker", "SessionTracker.toc" },
}
-- Hush modules: their versions matter for "update available", not for the news.
local modules = {
  { "hush-feed", "Hush_Feed", "Hush_Feed.toc" },
  { "hush-lfg", "Hush_LFG", "Hush_LFG.toc" },
  { "hush-recruit", "Hush_Recruit", "Hush_Recruit.toc" },
}

local function readf(p) local f = io.open(p, "rb"); if not f then return nil end local s = f:read("*a"); f:close(); return (s:gsub("\r\n", "\n")) end

local function tocField(text, field)
  return text:match("\n## " .. field .. ":%s*([^\n]*)") or text:match("^## " .. field .. ":%s*([^\n]*)")
end

local function gitDate(repo, path)
  local p = io.popen('git -C "' .. repo .. '" log -1 --format=%cs -- ' .. path .. " 2>nul")
  if not p then return nil end
  local d = p:read("*l"); p:close()
  return d and d:match("^%d%d%d%d%-%d%d%-%d%d$")
end

-- The first changelog entry: its heading (version, date) and first bullet as one line.
local function topEntry(text)
  if not text then return nil end
  local heading, body = text:match("\n## ([^\n]*)\n(.-)\n## ")
  if not heading then heading, body = text:match("\n## ([^\n]*)\n(.*)$") end
  if not heading then return nil end
  local date = heading:match("(%d%d%d%d%-%d%d%-%d%d)")
  local bullet = body:match("^%s*%- (.-)\n%- ") or body:match("^%s*%- (.*)$") or ""
  bullet = bullet:gsub("\n%s*", " "):gsub("`", ""):gsub("%s+$", "")
  return date, bullet
end

local function shorten(s, n)
  if #s <= n then return s end
  local cut = s:sub(1, n):match("^(.*)%s") or s:sub(1, n)
  return cut:gsub("[%.,;:%-]+$", "") .. "..."
end

local function quote(s) return '"' .. s:gsub("\\", "\\\\"):gsub('"', '\\"') .. '"' end

local out = { "-- Generated by tools/gen_releases.lua - do not edit by hand.", "local _, HUB = ...", "", "HUB.releases = {" }
local generated = os.date("%Y-%m-%d")

local function add(id, folder, tocName, news)
  local repo = repos .. "/" .. folder
  local toc = readf(repo .. "/" .. tocName)
  if not toc then print("missing " .. repo) return end
  local version = tocField(toc, "Version") or "?"
  local line = ("    [%s] = { version = %s"):format(quote(id), quote(version))
  if news then
    local cl = readf(repo .. "/CHANGELOG.md")
    local date, note = topEntry(cl)
    date = date or gitDate(repo, "CHANGELOG.md") or gitDate(repo, tocName) or generated
    if note and note ~= "" then
      line = line .. (", date = %s, note = %s"):format(quote(date), quote(shorten(note, 95)))
    end
  end
  out[#out + 1] = line .. " },"
  print(id, version)
end

for _, a in ipairs(addons) do add(a[1], a[2], a[3], true) end
for _, a in ipairs(modules) do add(a[1], a[2], a[3], false) end
out[#out + 1] = "}"
out[#out + 1] = ""
out[#out + 1] = ("HUB.releasesGenerated = %s"):format(quote(generated))
out[#out + 1] = ""

local f = assert(io.open(here .. "/Releases.lua", "wb"))
f:write(table.concat(out, "\n"))
f:close()
print("wrote Releases.lua")
